# Generated by Django 5.0.7 on 2024-08-05 17:35

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='profile_photo',
            field=models.FileField(default='static/images/media/default_user.png', upload_to=user.models.user_image),
        ),
    ]
