# Generated by Django 5.0.7 on 2024-08-04 14:17

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=300)),
                ('publisher', models.CharField(max_length=400)),
                ('date', models.DateField(verbose_name='Publish Date')),
                ('summary', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('image', models.FileField(upload_to=store.models.book_image)),
            ],
        ),
    ]
