# Generated by Django 5.0.7 on 2024-08-04 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='store.book', unique=True, verbose_name='Book'),
        ),
    ]
