# Generated by Django 5.0.7 on 2024-08-05 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_inventory_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
    ]
