apiVersion: v1
kind: Secret
metadata:
  name: {{ include "book-bazaar.fullname" . }}-secret
  labels:
    {{- include "book-bazaar.labels" . | nindent 4 }}
type: Opaque
data:
  dbName: {{ .Values.env.dbName | b64enc | quote }}
  dbUser: {{ .Values.env.dbUser | b64enc | quote }}
  dbPassword: {{ .Values.env.dbPassword | b64enc | quote }}
  dbHost: {{ .Values.env.dbHost | b64enc | quote }}
  dbPort: {{ .Values.env.dbPort | toString | b64enc | quote }}
  awsStorageBucketName: {{ .Values.env.awsStorageBucketName | b64enc | quote }}
  awsRegion: {{ .Values.env.awsRegion | b64enc | quote }}
  cloudfrontDomain: {{ .Values.env.cloudfrontDomain | b64enc | quote }}
